name: 🔄 同步 Gist 节点文件

on:
  schedule:
    # 每隔30分钟运行一次 (高频更新模式)
    - cron: '*/30 * * * *'
  workflow_dispatch: # 允许手动触发
  push:
    branches: [ main ]
    paths: [ '.github/workflows/sync-gist.yml' ]

# 设置权限
permissions:
  contents: write
  actions: read

jobs:
  sync-gist:
    runs-on: ubuntu-latest
    
    steps:
    - name: 📦 检出代码
      uses: actions/checkout@v4
      with:
        token: ${{ github.token }}
        fetch-depth: 0
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Create nodes directory
      run: |
        mkdir -p nodes
        
    - name: Download Gist files
      run: |
        # Gist 基础URL
        GIST_BASE_URL="https://gist.githubusercontent.com/shuaidaoya/9e5cf2749c0ce79932dd9229d9b4162b/raw/45a4616a347cf5998fd9ef83d41d8a91ff314bc6"
        
        # 下载各种格式的订阅文件
        echo "📥 正在下载 all.yaml..."
        curl -fsSL "${GIST_BASE_URL}/all.yaml" -o nodes/all.yaml || echo "❌ all.yaml 下载失败"
        
        echo "📥 正在下载 base64.txt..."
        curl -fsSL "${GIST_BASE_URL}/base64.txt" -o nodes/base64.txt || echo "❌ base64.txt 下载失败"
        
        echo "📥 正在下载 history.yaml..."
        curl -fsSL "${GIST_BASE_URL}/history.yaml" -o nodes/history.yaml || echo "❌ history.yaml 下载失败"
        
        echo "📥 正在下载 mihomo.yaml..."
        curl -fsSL "${GIST_BASE_URL}/mihomo.yaml" -o nodes/mihomo.yaml || echo "❌ mihomo.yaml 下载失败"
        
    - name: Generate file info
      run: |
        # 生成文件信息
        echo "# 📊 节点文件信息" > nodes/README.md
        echo "" >> nodes/README.md
        echo "**更新时间**: $(date '+%Y-%m-%d %H:%M:%S UTC')" >> nodes/README.md
        echo "" >> nodes/README.md
        echo "| 文件名 | 大小 | 最后修改 |" >> nodes/README.md
        echo "|--------|------|----------|" >> nodes/README.md
        
        for file in nodes/*.yaml nodes/*.txt; do
          if [ -f "$file" ]; then
            filename=$(basename "$file")
            filesize=$(ls -lh "$file" | awk '{print $5}')
            modified=$(date -r "$file" '+%Y-%m-%d %H:%M')
            echo "| $filename | $filesize | $modified |" >> nodes/README.md
          fi
        done
        
        echo "" >> nodes/README.md
        echo "> 🔄 文件每30分钟自动更新，确保节点的新鲜度和可用性" >> nodes/README.md
        
    - name: Count nodes
      id: count
      run: |
        # 统计节点数量
        total_nodes=0
        yaml_nodes=0
        base64_lines=0
        
        if [ -f "nodes/all.yaml" ]; then
          yaml_nodes=$(grep -c "server:" nodes/all.yaml 2>/dev/null || echo "0")
          total_nodes=$((total_nodes + yaml_nodes))
          echo "yaml_nodes=$yaml_nodes" >> $GITHUB_OUTPUT
        fi
        
        if [ -f "nodes/base64.txt" ]; then
          base64_lines=$(wc -l < nodes/base64.txt 2>/dev/null || echo "0")
          total_nodes=$((total_nodes + base64_lines))
          echo "base64_lines=$base64_lines" >> $GITHUB_OUTPUT
        fi
        
        echo "total_nodes=$total_nodes" >> $GITHUB_OUTPUT
        echo "📊 统计到 $total_nodes 个节点 (YAML: $yaml_nodes, Base64: $base64_lines)"
        
    - name: Update main README
      run: |
        # 更新主README中的统计信息
        current_date=$(date '+%Y-%m-%d %H:%M:%S')
        current_utc=$(date -u '+%Y-%m-%d %H:%M:%S UTC')
        total_nodes="${{ steps.count.outputs.total_nodes }}"
        yaml_nodes="${{ steps.count.outputs.yaml_nodes }}"
        base64_lines="${{ steps.count.outputs.base64_lines }}"
        
        # 更新实时统计区域
        if [ -f "README.md" ]; then
          # 使用 sed 更新 AUTO_STATS 区域内的统计信息
          sed -i '/<!-- AUTO_STATS_START -->/,/<!-- AUTO_STATS_END -->/{
            s/| 🕐 \*\*最后更新时间\*\* | .* |/| 🕐 **最后更新时间** | '"$current_utc"' |/
            s/| 🌐 \*\*节点总数\*\* | .* |/| 🌐 **节点总数** | '"$total_nodes"' 个 |/
            s/| 📄 \*\*YAML 节点\*\* | .* |/| 📄 **YAML 节点** | '"$yaml_nodes"' 个 |/
            s/| 📝 \*\*Base64 行数\*\* | .* |/| 📝 **Base64 行数** | '"$base64_lines"' 行 |/
            s/| 🔄 \*\*同步状态\*\* | .* |/| 🔄 **同步状态** | 🟢 已同步 |/
          }' README.md
          
          # 在更新日志表格中添加新的自动同步记录
          # 检查是否已存在今天的自动更新记录
          today_date=$(date '+%Y-%m-%d')
          
          # 生成节点详情描述（在条件判断外定义，确保两个分支都能使用）
          node_details="📊 自动更新"
          if [ "$yaml_nodes" -gt 0 ] && [ "$base64_lines" -gt 0 ]; then
            node_details="📊 自动更新 - YAML:${yaml_nodes}个 Base64:${base64_lines}行"
          elif [ "$yaml_nodes" -gt 0 ]; then
            node_details="📊 自动更新 - YAML节点:${yaml_nodes}个"
          elif [ "$base64_lines" -gt 0 ]; then
            node_details="📊 自动更新 - Base64:${base64_lines}行"
          fi
          
          if ! grep -q "| $today_date.*📊 自动更新" README.md; then
            # 在表格头部后面插入新记录
            sed -i '/|------|------|----------|/a\| '"$current_date"' | '"$total_nodes"'个节点 | '"$node_details"' |' README.md
            echo "✅ 已添加新的更新日志记录: $current_date - $total_nodes 个节点"
          else
            # 如果今天已有记录，则更新现有记录
            sed -i "s/| $today_date.*| [^|]* | .*📊 自动更新.* |/| $current_date | ${total_nodes}个节点 | $node_details |/" README.md
            echo "✅ 已更新今天的更新日志记录"
          fi
          
          echo "✅ README.md 实时统计和更新日志已更新"
        fi
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # 检查是否有变更
        if [ -n "$(git status --porcelain)" ]; then
          git add .
          git commit -m "🔄 自动更新节点文件 - $(date '+%Y-%m-%d %H:%M:%S')"
          git push
          echo "✅ 文件已更新并推送到仓库"
        else
          echo "ℹ️ 没有检测到文件变更"
        fi
      env:
        GITHUB_TOKEN: ${{ github.token }}
        
    - name: Create release summary
      run: |
        echo "## 📊 同步结果" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**同步时间**: $(date '+%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_STEP_SUMMARY
        echo "**节点总数**: ${{ steps.count.outputs.total_nodes }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 📁 文件状态" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        for file in nodes/*.yaml nodes/*.txt; do
          if [ -f "$file" ]; then
            filename=$(basename "$file")
            filesize=$(ls -lh "$file" | awk '{print $5}')
            echo "- ✅ **$filename**: $filesize" >> $GITHUB_STEP_SUMMARY
          fi
        done
        
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "🎉 **同步完成！所有文件已成功更新到仓库**" >> $GITHUB_STEP_SUMMARY